### ISSUE TITLE
Innovative idea! Screen goes black after first grabcut

### ISSUE THREAD

**Issue by BrainFeverMedia** [koooootake/Portrait-without-Depth-ios#3]
I'm testing this on iPad iOS13 with OpenCV 3.4.5.
After first grabcut with the rectangle, screen goes black and does not show segmentEditView.
Thank you if you have any suggestions.

**Comment by koooootake** [comment]
Thank you for the report.
I'll check.

**Comment by koooootake** [comment]
@BrainFeverMedia 
What is the version of Xcode you are using ?

**Comment by koooootake** [comment]
I updated the 'CropViewController' library and now it works on -Xcode11.2.1.
Thank you for the report🎉🎉🎉

**Comment by BrainFeverMedia** [comment]
Works great now. Thanks!
