### ISSUE TITLE
Issues with GrabCut with markers

### ISSUE THREAD

**Issue by DanielZanchi** [koooootake/Portrait-without-Depth-ios#4]
I'm trying to use part of this in my app:

I have an ImageView (with the original image to be cut) and on top of it there the DrawImageView (where I draw). 

I call _doGrabCutWithMask_() after _touchesEnded_(...) on my DrawImageView.
If i do a preview of the value in _drawImg_ and _markersImg_ in:
```
if let drawImg = drawView.image, let markersImg = cropInsideRectAndResize(image: drawImg, size: img.size) {
            DispatchQueue.global(qos: .default).async {
                let mask = OpenCVManager.shared()?.doGrabCut(img, markersImage: markersImg, iterationCount: 1)
                DispatchQueue.main.async {
                    self.imageView.image = mask
                }
            }
        } else {
        }
```

I can see the images correctly but it crashes at _doGrabCut_(...) saying:
grabcut.cpp:542: error: (-5:Bad argument) image is empty in function 'grabCut'
This happens if I set my bezierpath to a red color. 
If i set the path to a white color (how you did) it crashes inside the OpenCVManager.mm at line 117

maskMat on line 105 seems to be empty, but I can't understand why.

Can you help?

**Comment by DanielZanchi** [comment]
I was excluding the first part, not calling _doGrabCutWithRect_(), i don't want to do an automatic GrabCut. 
Is there a way to exclude it?

**Comment by koooootake** [comment]
Thank you for using.

If you annotate the image foreground or background with "red" color,
you have to change this code.
https://github.com/koooootake/Portrait-without-Depth-ios/blob/master/Portrait/OpenCV/OpenCVManager.mm#L110


If the image does not have an alpha value,
you have to change surrounding code.
https://github.com/koooootake/Portrait-without-Depth-ios/blob/master/Portrait/OpenCV/OpenCVManager.mm#L89


About the last question, GrabCut is the algorithm

> Initially user draws a rectangle around the foreground region (foreground region should be completely inside the rectangle). Then algorithm segments it iteratively to get the best result. 
https://docs.opencv.org/master/d8/d83/tutorial_py_grabcut.html

If you need to exclude the first step, you should use a different algorithm.


I'm happy if you can help.

**Comment by DanielZanchi** [comment]
Thank you for the reply. 

I think I managed to let it work. 
I see that, when it segments the image, the foreground mask creates a _white_ layer with some opacity, while the background is displayed as original. Is it possible to have this inverted? I would like to have a white layer on the background.

Thank you.

**Comment by koooootake** [comment]
Yes, you can.

You have to change this code.

https://github.com/koooootake/Portrait-without-Depth-ios/blob/master/Portrait/OpenCV/OpenCVManager.mm#L110
```swift
if(red == 0 && green == 0 && blue == 0 && alpha == 255) {//black is foreground
    data[width * y + x] = cv::GC_FGD;
    countFGD++;
} else if(red == 255 && green == 255 && blue == 255 && alpha == 255) {//white is background
    data[width * y + x] = cv::GC_BGD;
    countBGD++;
} else {
    countRem++;
}
```

If there is anything you don't understand, please ask.

**Comment by DanielZanchi** [comment]
What about  if I want to use the mask to remove the background instead of having it blurred?

**Comment by koooootake** [comment]
Blurring the background has nothing to do with GrabCut algorithm.

The image with the background removed by GrabCut and the blurred image are simply combined with the code around here.
https://github.com/koooootake/Portrait-without-Depth-ios/blob/master/Portrait/OpenCV/OpenCVManager.mm#L176

If you want to get the image with the background removed, remove the combining process.

**Comment by DanielZanchi** [comment]
I was trying to achieve this in swift (I don’t know how to use openCV) applying the mask image to the imageview with imageview.mask but nothing happens 😟
